name: taskly_bloc
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  bloc: ^9.0.1
  drift: ^2.30.0
  drift_flutter: ^0.2.8
  drift_sqlite_async: ^0.2.6
  envied: ^1.3.2
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_form_builder: ^10.2.0
  flutter_localizations:
    sdk: flutter
  form_builder_extra_fields: ^12.1.0
  form_builder_validators: ^11.2.0
  get_it: ^9.2.0
  go_router: ^17.0.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  logging: ^1.3.0
  path: ^1.9.1
  path_provider: ^2.1.5
  powersync: ^1.16.2
  smooth_sheets: ^0.15.0
  supabase_flutter: ^2.10.3
  uuid: ^4.4.2
  wolt_modal_sheet: ^0.11.0
dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.10.4
  drift_dev: ^2.30.0
  envied_generator: ^1.3.2
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  freezed_annotation: ^3.1.0
  json_serializable: ^6.9.5
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0
flutter:
  generate: true
  uses-material-design: true
