name: taskly_ui
publish_to: none
description: Shared pure-UI components for Taskly.

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  flex_color_picker: ^3.6.0
  flutter:
    sdk: flutter
  flutter_form_builder: ^10.2.0
  rrule: ^0.2.15

flutter:
  uses-material-design: true
