name: taskly_ui
publish_to: none
description: Shared pure-UI components for Taskly.

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  flex_color_picker: ^3.6.0
  flutter:
    sdk: flutter
  flutter_form_builder: ^10.2.0
  material_symbols_icons: ^4.2892.0

dev_dependencies:
  build_runner: ^2.4.12
  flutter_test:
    sdk: flutter
  meta: ^1.17.0
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
