name: taskly_core
publish_to: 'none'

environment:
  sdk: ^3.9.0

dependencies:
  characters: any
  flutter:
    sdk: flutter
  meta: any
  path_provider: any
  talker_flutter: any

dev_dependencies:
  flutter_test:
    sdk: flutter
