name: taskly_core
publish_to: 'none'

environment:
  sdk: ^3.9.0

dependencies:
  characters: any
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  meta: any
  path_provider: any
  talker_flutter: any
