name: taskly_domain
publish_to: 'none'

environment:
  sdk: ^3.9.0

dependencies:
  equatable: any
  flutter:
    sdk: flutter
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  logging: ^1.3.0
  meta: any
  ml_linalg: ^13.12.6
  rrule: any
  rxdart: any
  statistics: ^1.2.1
  taskly_core:
    path: ../taskly_core
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.12
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  json_serializable: ^6.9.5
  mocktail: ^1.0.3
  very_good_analysis: ^9.0.0

