name: taskly_domain
publish_to: 'none'

environment:
  sdk: ^3.9.0

dependencies:
  collection: ^1.19.0
  equatable: any
  flutter:
    sdk: flutter
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  meta: any
  ml_linalg: ^13.12.6
  rxdart: any
  statistics: ^1.2.1
  supabase_flutter: ^2.10.3
  taskly_core:
    path: ../taskly_core

dev_dependencies:
  build_runner: ^2.4.12
  freezed: ^3.2.3
  json_serializable: ^6.9.5

